version: '3.8'
services:
  redis_master_1:
    image: 'redis:latest'
    container_name: redis_master_1
    volumes:
      - redis_master_1_data:/data
      - ./redis1.conf/:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    network_mode: bridge
    ports: ['6379:6379', '16379:16379']

  redis_master_2:
    image: 'redis:latest'
    container_name: redis_master_2
    volumes:
      - redis_master_2_data:/data
      - ./redis2.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    network_mode: bridge
    ports: ['6380:6380', '16380:16380']

  redis_master_3:
    image: 'redis:latest'
    container_name: redis_master_3
    volumes:
      - redis_master_3_data:/data
      - ./redis3.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    network_mode: bridge
    ports: ['6381:6381', '16381:16381']

  redis_slave_1:
    image: 'redis:latest'
    container_name: redis_slave_1
    volumes:
      - redis_slave_1_data:/data
      - ./redis4.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    network_mode: bridge
    ports: ['6382:6382', '16382:16382']

  redis_slave_2:
    image: 'redis:latest'
    container_name: redis_slave_2
    volumes:
      - redis_slave_2_data:/data
      - ./redis5.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    network_mode: bridge
    ports: ['6383:6383', '16383:16383']

  redis_slave_3:
    image: 'redis:latest'
    container_name: redis_slave_3
    volumes:
      - redis_slave_3_data:/data
      - ./redis6.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    network_mode: bridge
    ports: ['6384:6384', '16384:16384']

volumes:
  redis_master_1_data: {}
  redis_master_2_data: {}
  redis_master_3_data: {}
  redis_slave_1_data: {}
  redis_slave_2_data: {}
  redis_slave_3_data: {}
