version: '3.8'
services:
  redis_master_1:
    image: 'redis:latest'
    container_name: redis_master_1
    volumes:
      - redis_master_1_data:/data
      - ./redis1.conf/:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports: ['6379:6379', '16379:16379']
    environment:
      - 'REDIS_NODES=redis_master_1 redis_master_2 redis_master_3 redis_slave_1 redis_slave_2 redis_slave_3'
    networks:
        redis_network:
          ipv4_address: 172.24.2.2

  redis_master_2:
    image: 'redis:latest'
    container_name: redis_master_2
    volumes:
      - redis_master_2_data:/data
      - ./redis2.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports: ['6380:6380', '16380:16380']
    environment:
      - 'REDIS_NODES=redis_master_1 redis_master_2 redis_master_3 redis_slave_1 redis_slave_2 redis_slave_3'
    networks:
        redis_network:
          ipv4_address: 172.24.2.3

  redis_master_3:
    image: 'redis:latest'
    container_name: redis_master_3
    volumes:
      - redis_master_3_data:/data
      - ./redis3.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports: ['6381:6381', '16381:16381']
    environment:
      - 'REDIS_NODES=redis_master_1 redis_master_2 redis_master_3 redis_slave_1 redis_slave_2 redis_slave_3'
    networks:
        redis_network:
          ipv4_address: 172.24.2.4

  redis_slave_1:
    image: 'redis:latest'
    container_name: redis_slave_1
    volumes:
      - redis_slave_1_data:/data
      - ./redis4.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports: ['6382:6382', '16382:16382']
    environment:
      - 'REDIS_NODES=redis_master_1 redis_master_2 redis_master_3 redis_slave_1 redis_slave_2 redis_slave_3'
    networks:
        redis_network:
          ipv4_address: 172.24.2.5

  redis_slave_2:
    image: 'redis:latest'
    container_name: redis_slave_2
    volumes:
      - redis_slave_2_data:/data
      - ./redis5.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports: ['6383:6383', '16383:16383']
    environment:
      - 'REDIS_NODES=redis_master_1 redis_master_2 redis_master_3 redis_slave_1 redis_slave_2 redis_slave_3'
    networks:
        redis_network:
          ipv4_address: 172.24.2.6

  redis_slave_3:
    image: 'redis:latest'
    container_name: redis_slave_3
    volumes:
      - redis_slave_3_data:/data
      - ./redis6.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports: ['6384:6384', '16384:16384']
    environment:
      - 'REDIS_NODES=redis_master_1 redis_master_2 redis_master_3 redis_slave_1 redis_slave_2 redis_slave_3'
    networks:
        redis_network:
          ipv4_address: 172.24.2.7

volumes:
  redis_master_1_data: {}
  redis_master_2_data: {}
  redis_master_3_data: {}
  redis_slave_1_data: {}
  redis_slave_2_data: {}
  redis_slave_3_data: {}

networks:
  # default:
  #   name: redis_network    # Use a custom driver
  redis_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/16"